project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /core/mspklarna/lexicon/en/*.inc.php
    translation: /core/mspklarna/lexicon/%two_letters_code%/%original_file_name%
  - source: /docs/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
    ignore:
      - /docs/index.md
