files:
  - source: /core/mspklarna/lexicon/en/*.inc.php
    translation: /core/mspklarna/lexicon/%two_letters_code%/%original_file_name%
  - source: /docs/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
