<?php

namespace alroniks\mspklarna\dto;

use Spatie\DataTransferObject\DataTransferObjectCollection;

class OrderCollection extends DataTransferObjectCollection
{
    public function current()
    {
        return parent::current(); // TODO: Change the autogenerated stub
    }
}
